### ISSUE TITLE
Can't do partition of data while running AdPart

### ISSUE THREAD

**Issue by Saptaparnineogi** [razen-alharbi/AdPart#2]
Hi,
We are trying to run AdPart in our cluster. It works fine when we run it in one machine locally but when we use cluster and try to do partitioning of data with partition value more than 1 we get the following error: 

mpirun noticed that the job aborted, but has no info as to the process
that caused that situation.
--------------------------------------------------------------------------
bash: orted: command not found
--------------------------------------------------------------------------
A daemon (pid 32061) died unexpectedly with status 127 while attempting
to launch so we are aborting.

There may be more information reported by the environment (see above).

This may be because the daemon was unable to find all the needed shared
libraries on the remote node. You may set your LD_LIBRARY_PATH to have the
location of the shared libraries on the remote nodes and this will
automatically be forwarded to the remote nodes.

We have all system requirement installed in our master node including MPICH. But from the error is looks like nodes are not able to communicate with each other while creating the partition of Data. Does MPICH needs to be installed in all machines in the cluster ? Or is there any specific requirement which needs to be satisfied for running AdPart in cluster?
Can you please help us with some information ?

Thank you !!

**Comment by razen-alharbi** [comment]
You need to make sure that your environment is identical on all nodes. More
importantly, you need to make sure all libraries are installed on all nodes
and your .bashrc or .cshrc files are the same.

The executable should also be duplicated on all nodes at the same path
unless you have a shared file system.

You can also check the sanity of your environment by running a simple mpi
program like:

mpirun -np 2 -machinefile <path_to_machine_file> hostname

Regards,

Razen

**Comment by Saptaparnineogi** [comment]
Thank you for your reply!

When you say libraries do you need all of the the below mentioned requirements -

gcc 
g++ 
build-essential 
libopenssh-server 
libmpich2-dev 
libboost-dev 
libboost-iostreams-dev 
libboost-system-dev 
libboost-filesystem-dev 
libglu1-mesa-dev 
gnuplot 

Another thing is when we create cluster, AdPart-master folder get created automatically in other machines also. Does that mean shared library is working?

When we run this command : 
mpirun -np 2 -machinefile /home/nereda/AdPart-master/conf/c1 /home/nereda/AdPart-master/Release/parallel_partitioner  

we get error like -

0 - RUNTIME ERROR: Usage: ParallelEncoder <db_directory> <input_file_name>
RUNTIME ERROR: Usage: ParallelEncoder <db_directory> <input_file_name>

**Comment by razen-alharbi** [comment]
Yes, you need to duplicate the whole environment on all nodes because the
executable is running on all nodes.

For the second question, you need to supply the arguments as specified in
the message.

**Comment by Saptaparnineogi** [comment]
We installed all required libraries is our worker nodes but still we get the same error while doing partition= 2 or more.
So as per our understanding data distribution among worker node is not working. So is there any specific folder where should we keep our data files(.nt files) and select any particular folder as database directory while loading the data using UI?
Any help from your side will be really great to get the system run.
Thank you so much.

**Comment by razen-alharbi** [comment]
We can have a Skype meeting to better assist you.

**Comment by Saptaparnineogi** [comment]
Yes, that will be great. Please let me know a suitable time for you. If can drop you an email for the skype id if your email id is same which is mentioned in git.

**Comment by razen-alharbi** [comment]
Yes
